### ISSUE TITLE
AWS Costs for Infrastructure Implementation

### ISSUE THREAD

**Issue by louis-monier** [aws-solutions-library-samples/guidance-for-modernizing-electric-vehicle-charging-on-aws#115]
Hi there,

Do you have an estimate of the AWS expenses associated with deploying this infrastructure?

Many thanks

**Comment by galinsky** [comment]
We do not have any formal cost analyses but have run some scenario calculations (using [calculator.aws](https://calculator.aws/#/)). The cost varies based on number of chargers because scaling of containers is linear but a step growth with the growth of connected charge points. Just running the OCPP gateway (not the business logic triggered by OCPP actions), which includes Fargate, NLB, SQS, and IoT, is estimated to cost between $2 and $3 per charge point per year at scale. I would recommend connecting with your AWS SA to do a deeper dive on the economics of your specific use case.
